const fs = require('fs');

const JSON_DATA = \`
const GITA=[ {num:1,sk:'अर्जुन विषाद योग',ro:'Arjuna Vishada Yoga',en:'The Yoga of Arjuna\\\\\'s Grief',shloka:'धृतराष्ट्र उवाच —\\nधर्मक्षेत्रे कुरुक्षेत्रे समवेता युयुत्सवः।\\nमामकाः पाण्डवाश्चैव किमकुर्वत सञ्जय।।',trans:'"Dhritarashtra said: O Sanjaya, after my sons and the sons of Pandu assembled at Kurukshetra, desiring to fight, what did they do?"',lesson:'Even the greatest warrior can be paralysed by emotion. Acknowledging grief is the first step to wisdom.',modern:'Arjuna shows classic acute stress response symptoms — racing heart, trembling limbs, mental fog. Modern psychology calls this "crisis paralysis." The chapter normalises vulnerability as the starting point of transformation.',preview:'Arjuna sees his own teachers and relatives on the opposing side and drops his bow, unable to fight.',tags:['Grief','Duty','Paralysis']},
{num:2,sk:'सांख्य योग',ro:'Sankhya Yoga',en:'The Yoga of Knowledge',shloka:'न जायते म्रियते वा कदाचिन्\\nनायं भूत्वा भविता वा न भूयः।\\nअजो नित्यः शाश्वतोऽयं पुराणो\\nन हन्यते हन्यमाने शरीरे।।',trans:'"The soul is never born nor dies at any time. It has not come into being, does not come into being, and will not come into being. It is unborn, eternal, ever-existing, and primeval. It is not slain when the body is slain."',lesson:'You are not your body. Fear of death dissolves when you understand the self is eternal.',modern:'Relates to "self-transcendence" in psychology — detaching identity from the physical. Also connects to terror management theory: awareness of soul\\\\\'s immortality reduces existential anxiety at a neurological level.',preview:'Krishna explains the eternal nature of the soul and the philosophy of Sankhya to calm Arjuna\\\\\'s grief.',tags:['Soul','Immortality','Knowledge']},
{num:3,sk:'कर्म योग',ro:'Karma Yoga',en:'The Yoga of Action',shloka:'नियतं कुरु कर्म त्वं कर्म ज्यायो ह्यकर्मणः।\\nशरीरयात्रापि च ते न प्रसिद्ध्येदकर्मणः।।',trans:'"Do your duty. Action is better than inaction. Even the maintenance of your body would not be possible without action."',lesson:'Do your duty without craving results. Action done selflessly purifies the soul.',modern:'Behavioural science calls this "intrinsic motivation" — working for the work itself, not the reward. Intrinsically motivated people consistently outperform extrinsically motivated ones in complex, creative tasks.',preview:'Krishna teaches that one must act according to duty without attachment to the fruits of action.',tags:['Action','Duty','Selfless Work']},
{num:4,sk:'ज्ञान कर्म संन्यास योग',ro:'Jnana Karma Sanyasa Yoga',en:'The Yoga of Knowledge & Renunciation',shloka:'यदा यदा हि धर्मस्य ग्लानिर्भवति भारत।\\nअभ्युत्थानमधर्मस्य तदात्मानं सृजाम्यहम्।।',trans:'"Whenever there is a decline of righteousness and rise of unrighteousness, O Arjuna, I manifest Myself. For the protection of the good, the destruction of the wicked, and the establishment of righteousness, I am born from age to age."',lesson:'Knowledge liberates. God descends when dharma declines. Truth is cyclical, not linear.',modern:'Jungian psychology speaks of the "archetypal hero" appearing in the collective unconscious when society is in shadow — an independent discovery of the same idea 2400 years later.',preview:'Krishna reveals He appears whenever righteousness declines, and teaches the path of wisdom and divine incarnation.',tags:['Knowledge','Incarnation','Dharma']},
{num:5,sk:'कर्म संन्यास योग',ro:'Karma Sanyasa Yoga',en:'The Yoga of Renunciation of Action',shloka:'संन्यासः कर्मयोगश्च निःश्रेयसकरावुभौ।\\nतयोस्तु कर्मसंन्यासात्कर्मयोगो विशिष्यते।।',trans:'"Both renunciation of action and action in devotion are good for liberation. But of the two, action in devotion is better than renunciation of action."',lesson:'True renunciation is not running away — it is acting without ego.',modern:'Stoic philosophy: "amor fati" — love of fate, acting fully while detached from outcome. Marcus Aurelius wrote the same principle in Meditations, 700 years after the Gita.',preview:'Krishna compares renunciation with action-in-devotion, declaring the second superior for ordinary human life.',tags:['Renunciation','Ego','Liberation']},
{num:6,sk:'आत्मसंयम योग',ro:'Atma Sanyam Yoga',en:'The Yoga of Self-Control & Meditation',shloka:'उद्धरेदात्मनात्मानं नात्मानमवसादयेत्।\\nआत्मैव ह्यात्मनो बन्धुरात्मैव रिपुरात्मनः।।',trans:'"Let a man lift himself by his own Self alone; let him not lower himself, for this self alone is the friend of oneself, and this self alone is the enemy of oneself."',lesson:'You are your own best friend and your own worst enemy. Discipline is the highest form of self-love.',modern:'Self-determination theory: internal locus of control predicts wellbeing more than any external factor. Meditation practice is now backed by 10,000+ neuroscience studies showing measurable structural brain changes.',preview:'A detailed practical guide to meditation — posture, breathing, the restless mind, and how to return to stillness.',tags:['Meditation','Self-Control','Mind']},
{num:7,sk:'ज्ञान विज्ञान योग',ro:'Jnana Vijnana Yoga',en:'The Yoga of Knowledge & Realisation',shloka:'मनुष्याणां सहस्रेषु कश्चिद्यतति सिद्धये।\\nयततामपि सिद्धानां कश्चिन्मां वेत्ति तत्त्वतः।।',trans:'"Among thousands of men, scarcely one strives for perfection; and of those who strive and succeed, scarcely one knows Me in truth."',lesson:'Seeking truth is rare. Knowing truth is rarer still. Both are worth everything.',modern:'The Dunning-Kruger effect inverted: the truly wise always know how little they know. Socrates said: "I know that I know nothing." Intellectual humility is the strongest predictor of better decision-making across all domains.',preview:'Krishna explains the divine nature and how very few among humanity truly seek or attain genuine spiritual knowledge.',tags:['Wisdom','God','Reality']},
{num:8,sk:'अक्षर ब्रह्म योग',ro:'Aksara Brahma Yoga',en:'The Yoga of the Imperishable Absolute',shloka:'अन्तकाले च मामेव स्मरन्मुक्त्वा कलेवरम्।\\nयः प्रयाति स मद्भावं याति नास्त्यत्र संशयः।।',trans:'"Whoever, at the time of death, gives up the body remembering Me alone, reaches My state. Of this there is no doubt."',lesson:'What you think at your final moment reflects your entire life\\\\\'s deepest habit. Live accordingly today.',modern:'Neurologically, the dying brain consolidates the patterns most reinforced throughout life. Final thoughts literally mirror lifelong mental habits — every moment of practice matters.',preview:'Krishna explains what happens to the soul at death and how consistent meditation practice determines one\\\\\'s destination.',tags:['Death','Liberation','Consciousness']},
{num:9,sk:'राज विद्या राज गुह्य योग',ro:'Raja Vidya Raja Guhya Yoga',en:'The Yoga of Royal Knowledge',shloka:'अनन्याश्चिन्तयन्तो मां ये जनाः पर्युपासते।\\nतेषां नित्याभियुक्तानां योगक्षेमं वहाम्यहम्।।',trans:'"For those who worship Me with devotion, meditating on My transcendental form — I carry what they lack and preserve what they have."',lesson:'Surrender is not weakness. Complete devotion to a higher purpose carries you through what effort alone cannot.',modern:'Flow state research (Csikszentmihalyi): complete absorption in something beyond the ego produces peak performance and sustained wellbeing. The self disappears, and excellence flows naturally.',preview:'Called the "king of all knowledge" — this chapter reveals the supreme mystery of devotion and Krishna\\\\\'s direct promise to His devotees.',tags:['Devotion','Surrender','Grace']},
{num:10,sk:'विभूति योग',ro:'Vibhuti Yoga',en:'The Yoga of Divine Manifestation',shloka:'अहमात्मा गुडाकेश सर्वभूताशयस्थितः।\\nअहमादिश्च मध्यं च भूतानामन्त एव च।।',trans:'"I am the Self, O Arjuna, dwelling in the heart of all beings. I am the beginning, the middle, and the end of all beings."',lesson:'The divine is not outside you. It is the intelligence inside every atom, every life, every thought.',modern:'Panpsychism — the modern philosophy that consciousness is a fundamental property of reality — now seriously engaged by physicists like Roger Penrose. The Gita articulated this 2500 years earlier.',preview:'Krishna describes His infinite manifestations — every river, every mountain, every silence — giving Arjuna a map of the divine in everything.',tags:['Divine','Manifestation','Self']},
{num:11,sk:'विश्वरूप दर्शन योग',ro:'Vishwarupa Darshana Yoga',en:'The Yoga of the Cosmic Form',shloka:'कालोऽस्मि लोकक्षयकृत्प्रवृद्धो\\nलोकान्समाहर्तुमिह प्रवृत्तः।',trans:'"I am Time, the great destroyer of worlds, and I have come here to destroy all people. With the exception of you, all the soldiers here on both sides will be slain."',lesson:'Time is the ultimate reality. It consumes everything. Act now. Every delay is a small death.',modern:'Terror Management Theory (Ernest Becker): awareness of death is paradoxically the greatest driver of meaningful human action. The Gita arrived at this insight 2500 years before modern psychology.',preview:'The most dramatic chapter — Arjuna is granted divine vision and sees Krishna\\\\\'s infinite, terrifying cosmic form devouring all of creation.',tags:['Cosmic Form','Time','Destruction']},
{num:12,sk:'भक्ति योग',ro:'Bhakti Yoga',en:'The Yoga of Devotion',shloka:'मय्येव मन आधत्स्व मयि बुद्धिं निवेशय।\\nनिवसिष्यसि मय्येव अत ऊर्ध्वं न संशयः।।',trans:'"Fix your mind on Me alone, let your intellect dwell in Me. Henceforth you shall live in Me. There is no doubt about this."',lesson:'Love is the shortest path. Devotion dissolves the ego faster than logic ever could.',modern:'Oxytocin (the bonding hormone) activates the brain\\\\\'s reward circuitry. Sustained devotion and deep love literally restructure neural pathways, reducing amygdala fear responses measurably.',preview:'A gentle, intimate chapter where Krishna describes the qualities of His most beloved devotee — equanimity, compassion, freedom from ego.',tags:['Devotion','Love','Bhakti']},
{num:13,sk:'क्षेत्र क्षेत्रज्ञ विभाग योग',ro:'Kshetra Kshetragyna Vibhaga Yoga',en:'The Yoga of the Field and Its Knower',shloka:'इदं शरीरं कौन्तेय क्षेत्रमित्यभिधीयते।\\nएतद्यो वेत्ति तं प्राहुः क्षेत्रज्ञ इति तद्विदः।।',trans:'"This body, O son of Kunti, is called the field. One who knows this body is called the knower of the field by those who know of it."',lesson:'You are not your body. The body is the field; you are the farmer. Know the difference.',modern:'This maps onto the neuroscience of the "observer self" — the meta-awareness that watches thoughts without being them. It is the entire basis of mindfulness and Cognitive Behavioural Therapy.',preview:'A philosophical dissection of matter vs. consciousness — distinguishing what you are from what you merely inhabit.',tags:['Body','Soul','Self-Knowledge']},
{num:14,sk:'गुणत्रय विभाग योग',ro:'Gunatraya Vibhaga Yoga',en:'The Yoga of the Three Qualities',shloka:'सत्त्वं रजस्तम इति गुणाः प्रकृतिसम्भवाः।\\nनिबध्नन्ति महाबाहो देहे देहिनमव्ययम्।।',trans:'"Sattva, Rajas, and Tamas — these three qualities, born of material nature, bind the eternal soul to the body, O mighty-armed one."',lesson:'Every action, food, thought, and person either raises your energy (Sattva), agitates it (Rajas), or dulls it (Tamas). Choose deliberately.',modern:'Modern behavioural energy management maps human states as "high-positive" (Sattva), "high-negative" (Rajas), and "low-negative" (Tamas) — the same classification system, independently derived.',preview:'The three gunas framework — a classification of all matter, food, actions, and mental states that shapes every aspect of life.',tags:['Sattva','Rajas','Tamas','Energy']},
{num:15,sk:'पुरुषोत्तम योग',ro:'Purushottama Yoga',en:'The Yoga of the Supreme Person',shloka:'ऊर्ध्वमूलमधःशाखमश्वत्थं प्राहुरव्ययम्।\\nछन्दांसि यस्य पर्णानि यस्तं वेद स वेदवित्।।',trans:'"They speak of an eternal peepal tree with its roots above and branches below, whose leaves are the Vedic hymns. One who knows this tree is the knower of the Vedas."',lesson:'Reality is an inverted tree — roots above in consciousness, branches below in matter. Seek the source, not the branches.',modern:'Systems thinking and emergence theory: visible complex phenomena arise from invisible foundational principles. The "roots up" logic underlies all of modern computational and network science.',preview:'The mysterious metaphor of the inverted cosmic tree — and Krishna\\\\\'s revelation of the Supreme Person beyond both the perishable and imperishable.',tags:['Supreme Self','Reality','Consciousness']},
{num:16,sk:'दैवासुर सम्पद विभाग योग',ro:'Daivāsura Sampad Vibhaga Yoga',en:'The Yoga of Divine & Demonic Qualities',shloka:'अभयं सत्त्वसंशुद्धिर्ज्ञानयोगव्यवस्थितिः।\\nदानं दमश्च यज्ञश्च स्वाध्यायस्तप आर्जवम्।।',trans:'"Fearlessness, purity of heart, steadfastness in knowledge and yoga, charity, self-control, sacrifice, study of scriptures, austerity, straightforwardness..."',lesson:'Every human contains both divine and demonic tendencies. Awareness is what lets you choose which one grows.',modern:'Jungian shadow work: acknowledging the dark side of the personality is the first step to integrating and transcending it. The Gita\\\\\'s divine/demonic split maps precisely onto Jung\\\\\'s persona and shadow archetypes.',preview:'A vivid catalogue of divine qualities (fearlessness, compassion, honesty) vs. demonic qualities (arrogance, cruelty) — and which path each leads to.',tags:['Dharma','Character','Good vs Evil']},
{num:17,sk:'श्रद्धात्रय विभाग योग',ro:'Shradhatraya Vibhaga Yoga',en:'The Yoga of the Threefold Faith',shloka:'त्रिविधा भवति श्रद्धा देहिनां सा स्वभावजा।\\nसात्त्विकी राजसी चैव तामसी चेति तां शृणु।।',trans:'"The faith of each person is in accordance with their natural disposition. A person is made of faith; whatever their faith is, so are they."',lesson:'You become exactly what you believe. Faith is not just religion — it is the direction your entire life points.',modern:'The placebo effect, self-fulfilling prophecy, and confirmation bias all scientifically demonstrate that belief literally shapes physiological and social reality. The Gita stated this 2500 years before psychology.',preview:'Faith, food, worship, and charity divided by the three gunas — a practical framework for examining the quality of your daily choices.',tags:['Faith','Belief','Food','Worship']},
{num:18,sk:'मोक्ष संन्यास योग',ro:'Moksha Sanyasa Yoga',en:'The Yoga of Liberation & Renunciation',shloka:'सर्वधर्मान्परित्यज्य मामेकं शरणं व्रज।\\nअहं त्वां सर्वपापेभ्यो मोक्षयिष्यामि मा शुचः।।',trans:'"Abandon all varieties of religion and just surrender unto Me. I shall deliver you from all sinful reactions. Do not fear."',lesson:'The final teaching: let go of everything — roles, rules, duties, identities — and surrender completely. That is the ultimate freedom.',modern:'Psychologically maps onto radical acceptance and unconditional positive regard — the most advanced states in therapeutic healing. Total surrender of ego is where every contemplative tradition eventually arrives.',preview:'The longest chapter — a complete summary of the Gita, culminating in the most famous verse: Surrender to Me alone.',tags:['Liberation','Surrender','Final Teaching']}];

const PANCHA=[
{num:1,title:'मित्रभेद',ro:'Mitra Bheda',en:'The Loss of Friends',desc:'The longest and most famous book. A lion king Pingalaka and his bull friend Sanjeevaka are manipulated apart by the scheming jackal Damanaka, who fears losing his own influence. A masterclass in how envy, flattery, and political cunning can destroy the deepest bonds.',moral:'A clever tongue can destroy what years of friendship built. Beware those who benefit from your separation.',stories:[{t:'The Monkey and the Crocodile',s:'A monkey and a crocodile are friends. The crocodile\\\\\'s jealous wife demands the monkey\\\\\'s heart. The crocodile invites the monkey to cross the river on his back — then reveals the trap midway. The wise monkey claims he left his heart in the tree and must go back for it. The foolish crocodile turns back, and the monkey escapes forever.',l:'Greed destroys genuine friendship. A wise person thinks before the trap closes, not after.'},{t:'The Blue Jackal',s:'A hungry jackal falls into a tub of indigo dye. Emerging brilliant blue, he proclaims himself a divine animal sent by the gods. All animals bow. He banishes fellow jackals. One night, other jackals howl — instinct takes over, and he howls back. His true nature is revealed. He is killed by the animals he deceived.',l:'No false identity survives scrutiny forever. You cannot outrun what you actually are.'},{t:'The Lion and the Hare',s:'A tyrant lion terrorises the forest, demanding one animal daily. On the hare\\\\\'s turn, he arrives late, telling the lion a rival lion in a well delayed him. The enraged lion rushes to the well, sees his own reflection, and leaps in — drowning himself. The hare saves the forest without a single act of violence.',l:'Intelligence defeats strength every time. The best battle is the one where your enemy destroys himself.'}]},
{num:2,title:'मित्रसम्प्राप्ति',ro:'Mitra Samprapti',en:'The Gaining of Friends',desc:'A crow, a mouse, a tortoise, and a deer — four animals with nothing in common — form an unlikely, deeply loyal friendship. Each saves the others through their unique strengths. The book teaches that true friendship is built through service, and diversity of skills is the greatest strength of any alliance.',moral:'Friends who are different from you complete your blind spots. Seek allies, not mirrors.',stories:[{t:'The Crow, Mouse, Tortoise and Deer',s:'A deer is caught in a hunter\\\\\'s net. The mouse chews through the net. The tortoise distracts the hunter. The crow watches from above and warns of danger. Each animal contributes what the others cannot — and together they succeed where any one alone would have failed.',l:'Every weakness in a group is covered by someone else\\\\\'s strength. Build your circle for complementarity, not similarity.'},{t:'The Weaver Who Loved a Princess',s:'A poor weaver falls in love with a princess. His clever friend builds him a mechanical flying Vishnu chariot. The weaver flies to her window dressed as Lord Vishnu. The king, told of the divine visit, accepts the union as divine will.',l:'Audacity, creativity, and the right ally can achieve what conventional effort never could.'}]},
{num:3,title:'काकोलूकीयम्',ro:'Kakolukiyam',en:'Of Crows and Owls',desc:'The darkest book. Crows and owls are hereditary enemies. This is about war, truce, spying, and the mechanics of political betrayal between states that can never truly trust each other. Essentially a manual for strategic warfare dressed in animal fables.',moral:'Never trust an enemy who claims to have changed — demand proof. Never reveal your weakness to someone who benefits from it.',stories:[{t:'The Crow Who Infiltrated the Owls',s:'A crow volunteers to be "banished" by his own murder — beaten publicly to look real — then approaches the owl kingdom as a refugee. He earns their trust, lives in their fortress, learns every weakness, then guides his crow family to pile dry leaves at every entrance. They burn the owls in their own home.',l:'The most dangerous spy is one who earns your sympathy. Never allow an enemy inside your defenses.'},{t:'The Cave That Spoke',s:'Scouts report a lion\\\\\'s tracks entering a cave but not leaving. A wise crow suggests calling out: "O Cave, do you not welcome guests as usual?" The lion inside, confused, calls back "Come in!" — revealing himself. The crows fly away and warn the kingdom.',l:'Before entering any situation, test it safely from a distance. Intelligence is the first weapon.'}]},
{num:4,title:'लब्धप्रणाश',ro:'Labdhapranasha',en:'Loss of Gains',desc:'Short and punishing. A collection of stories about losing what you already have by grasping for more. The message is relentless: contentment is the greatest wealth; greed is the most reliable destroyer of all you have earned.',moral:'The bird in hand is worth ten in the sky. Greed is not ambition — it is the enemy of what you have already won.',stories:[{t:'The Monkey and the Wedge',s:'Merchants are building a temple. A monkey curiously sits on the half-split log, tail trapped in the wedge. He pulls out the wedge to free himself. The log snaps shut, crushing him. He dies for meddling in what was not his business.',l:'Interference in affairs that do not concern you always costs more than it gives.'},{t:'The Brahmin\\\\\'s Dream',s:'A brahmin receives a pot of barley flour. He fantasises: sell the flour, buy a goat, then cattle, then marry, have children. He waves his staff in fantasy to discipline his imaginary son — and knocks over the real pot. Every grain spills. He had nothing before; he has nothing now.',l:'Daydreaming about what you do not yet have guarantees you will lose what you do.'}]},
{num:5,title:'अपरीक्षितकारकम्',ro:'Aparikshitakarakam',en:'Ill-Considered Action',desc:'The final book. A sustained warning against acting without full inquiry. The most famous story in all of Panchatantra lives here. The message is not "think slowly" but "never act on incomplete information, especially when the stakes are irreversible."',moral:'Act only after full inquiry. Haste is the father of permanent regret. Ask one more question before you act.',stories:[{t:'The Brahmin and the Mongoose',s:'A brahmin leaves his baby sleeping, trusting their loyal mongoose to guard the child. He returns to find the mongoose at the door, mouth covered in blood. He instantly kills the mongoose with his water pot. He rushes inside to find his son safe, sleeping next to the crushed body of a deadly cobra the mongoose had killed to protect him. He destroyed his most loyal protector on an assumption.',l:'Never act on incomplete evidence. The most irreversible decisions demand the most patience.'},{t:'The Four Scholars and the Revived Lion',s:'Four scholars find a dead lion. Three want to revive it to prove their learning. The fourth, with only common sense, says "This will kill us." They ignore him. He climbs a tree. The three revive the lion with perfect knowledge. It eats them immediately.',l:'Practical wisdom outweighs academic knowledge every time. Before applying what you know, ask what the result actually is.'}]}];

const AYUR=[
{name:'अश्वगंधा',ro:'Ashwagandha',en:'Indian Ginseng / Winter Cherry',lat:'Withania somnifera',rasa:'Bitter, Astringent',guna:'Heavy, Oily',effect:'Vata-Kapha balancing',dosha:'Reduces Vata & Kapha',when:'Chronic stress, fatigue, low immunity, poor sleep, anxiety, low testosterone, post-illness recovery.',how:'½ tsp root powder in warm full-fat milk at night before sleep. Add honey after cooling. Or 300–500mg extract capsule.',dosage:'300–500mg standardised extract (with 5% withanolides) OR 1–2 tsp root powder daily. Most benefits seen after 8–12 weeks.',warn:'Avoid in pregnancy and lactation. Do not combine with thyroid medications without doctor supervision. May cause sedation.',sci:'50+ human clinical trials. Reduces serum cortisol by 27.9% (Chandrasekhar et al., 2012). Improves VO₂max in athletes. Withanolides modulate HPA axis stress response. Classified as adaptogen — helps body maintain homeostasis under physical and psychological stress.',tags:['Stress','Sleep','Immunity','Strength','Fatigue']},
{name:'तुलसी',ro:'Tulsi',en:'Holy Basil',lat:'Ocimum sanctum (tenuiflorum)',rasa:'Pungent, Bitter',guna:'Light, Dry',effect:'Vata-Kapha reducing',dosha:'Reduces Vata & Kapha',when:'Cold, cough, sore throat, fever, mild anxiety, low energy, respiratory issues, monsoon immunity.',how:'5–10 fresh leaves in 1 cup boiling water. Steep 5 minutes. Add ginger and honey. Drink morning on empty stomach.',dosage:'2–3 cups tulsi tea daily OR 300–600mg dried leaf capsule. Fresh leaves are most potent.',warn:'Avoid large doses during pregnancy (may stimulate uterine contractions). May slow blood clotting — stop 2 weeks before surgery.',sci:'Contains eugenol (anti-inflammatory), rosmarinic acid (antioxidant), and ursolic acid (adaptogenic). Studies show significant reduction in anxiety scores (GAD-7) and blood glucose. Anti-bacterial against E. coli, S. aureus, and H. pylori.',tags:['Cold','Immunity','Stress','Respiratory','Fever']},
{name:'हरिद्रा',ro:'Haridra',en:'Turmeric',lat:'Curcuma longa',rasa:'Pungent, Bitter, Astringent',guna:'Light, Dry',effect:'Tridoshic (balances all 3)',dosha:'Balances Vata, Pitta & Kapha',when:'Inflammation (joints, gut, skin), poor digestion, low immunity, wound healing, skin dullness, metabolic syndrome.',how:'Golden milk: ½ tsp turmeric + pinch of black pepper in warm milk. Black pepper increases curcumin absorption by 2000%. Can also cook in ghee.',dosage:'500–1000mg curcumin extract with piperine daily. For culinary use: ½–1 tsp in food. Always combine with black pepper or fat.',warn:'High doses thin blood — stop 2 weeks before surgery. Avoid with anticoagulants at therapeutic doses. Safe at culinary doses for everyone.',sci:'12,000+ research papers on curcumin. Inhibits NF-κB — the master switch of inflammation. Compares favourably to ibuprofen for knee osteoarthritis pain in 3 human trials. Phase II cancer trials ongoing.',tags:['Inflammation','Joints','Digestion','Skin','Immunity']},
{name:'त्रिफला',ro:'Triphala',en:'Three Fruits',lat:'Terminalia chebula + T. bellerica + Phyllanthus emblica',rasa:'Contains 5 of the 6 tastes — all except salty',guna:'Light, Dry',effect:'Tridoshic',dosha:'Balances all 3 doshas',when:'Constipation, sluggish digestion, detox, eye strain, weight management, anti-aging.',how:'1 tsp powder stirred into warm water at bedtime. Do not add honey until water cools. Or 2 capsules (500mg each) 30 min before bed.',dosage:'3–6g powder at night or 500–1000mg extract. Consistent use for 4–6 weeks for full gut-health benefits.',warn:'May cause loose stools initially — start with ½ tsp. Avoid during pregnancy. Do not take with iron supplements.',sci:'5x the Vitamin C of oranges per gram. Proven prebiotic — feeds Lactobacillus and Bifidobacterium. Tannins in Haritaki have proven anti-H. pylori activity. 600+ peer-reviewed papers.',tags:['Digestion','Detox','Eyes','Anti-aging','Constipation']},
{name:'ब्राह्मी',ro:'Brahmi',en:'Water Hyssop / Bacopa',lat:'Bacopa monnieri',rasa:'Bitter, Astringent, Sweet',guna:'Light',effect:'Tridoshic — especially Vata-Pitta',dosha:'Reduces Vata & Pitta',when:'Poor memory, brain fog, exam stress, ADHD, anxiety, slow learning speed, age-related cognitive decline.',how:'300mg standardised extract twice daily with food. Or ½ tsp Brahmi powder in ghee/milk. Brahmi oil: massage into scalp before bath.',dosage:'300–600mg extract standardised to 20% bacosides. Must take for minimum 12 weeks — effects are cumulative.',warn:'May cause nausea if taken on empty stomach — always take with food. Avoid with benzodiazepines or sedatives.',sci:'Bacosides A and B repair synaptic plasticity in the hippocampus. 12-week RCT (Stough et al.): significant improvement in verbal learning, memory consolidation, and visual processing speed vs. placebo. Inhibits acetylcholinesterase — same mechanism as Alzheimer\\\\\'s drugs, but gentler.',tags:['Memory','Brain','Anxiety','Focus','ADHD']},
{name:'आमलकी',ro:'Amalaki',en:'Indian Gooseberry / Amla',lat:'Phyllanthus emblica',rasa:'All 6 tastes — predominantly sour',guna:'Heavy, Cold, Moist',effect:'Tridoshic — especially Pitta reducing',dosha:'Strongly reduces Pitta',when:'Low immunity, hair fall/greying, acidity, vitamin C deficiency, premature aging, eye weakness, skin dullness.',how:'20–30ml fresh amla juice in morning on empty stomach. Or 1–2 dried amla chewed. Chyawanprash (stores) uses amla as primary ingredient.',dosage:'1–3g amla powder or 20–30ml fresh juice daily. Vitamin C content: ~600mg per 100g — highest natural food source.',warn:'Avoid at night (increases cold, Kapha). Don\\\\\'t take with antacids. Very high doses may disturb digestion.',sci:'Vitamin C content is extremely heat-stable (unlike synthetic ascorbic acid) — survives cooking and drying. Richest natural Vitamin C source globally. Ellagic acid extends cellular lifespan in vitro. Multiple human trials confirm lipid-lowering and blood sugar moderating effects.',tags:['Immunity','Hair','Vitamin C','Anti-aging','Digestion']},
{name:'नीम',ro:'Neem',en:'Indian Lilac',lat:'Azadirachta indica',rasa:'Bitter',guna:'Light, Dry',effect:'Reduces Pitta and Kapha',dosha:'Reduces Pitta & Kapha',when:'Skin problems (acne, eczema, fungal), blood purification, elevated blood sugar, dental infections, intestinal worms.',how:'4–5 fresh neem leaves chewed on empty stomach in morning. Neem-infused water for skin wash. Neem twig (datun) as natural toothbrush. Neem oil diluted in coconut oil for topical use.',dosage:'500mg dried leaf extract capsule daily OR 4–5 fresh leaves. For skin: neem oil diluted to 1–2% in carrier oil.',warn:'Never give to children under 2 years. Avoid if trying to conceive. Do not take during pregnancy.',sci:'Nimbidin and nimbin — proven antibacterial against 14 bacterial strains including MRSA. Azadirachtin disrupts parasite hormone systems. Multiple clinical trials confirm anti-glycaemic effects. WHO recognises neem as significant natural medicine.',tags:['Skin','Blood','Blood Sugar','Antibacterial','Dental']},
{name:'शतावरी',ro:'Shatavari',en:'Asparagus Root',lat:'Asparagus racemosus',rasa:'Sweet, Bitter',guna:'Heavy, Oily, Cold',effect:'Vata-Pitta balancing',dosha:'Reduces Vata & Pitta',when:'Hormonal imbalance (women), PCOD/PCOS support, low milk production, menopause symptoms, dryness, low energy.',how:'1 tsp Shatavari powder in warm full-fat milk with honey — morning or before bed. Combination with Ashwagandha enhances effect for general vitality.',dosage:'500mg–2g powder daily in milk or water. Take consistently for 2–3 months for hormonal effects.',warn:'Avoid with diuretics. May cause bloating initially. Not for men in very high doses without guidance.',sci:'Steroidal saponins (shatavarin I–IV) demonstrate phytoestrogen activity — modulate estrogen receptors without synthetic hormone risks. Human studies show significant increase in prolactin and milk volume in lactating women.',tags:['Women\\\\\'s Health','Hormones','Lactation','Energy','PCOD']},
{name:'गुग्गुल',ro:'Guggul',en:'Indian Bdellium / Commiphora resin',lat:'Commiphora wightii',rasa:'Bitter, Pungent, Astringent',guna:'Light, Dry',effect:'Reduces Kapha and Vata',dosha:'Reduces Kapha & Vata',when:'High cholesterol (LDL), joint pain, obesity, arthritis, hypothyroidism support, acne (internal cause).',how:'Tablet or capsule form — always purified (shuddha) guggul only. With warm water after meals. Often combined as Yogaraj Guggulu (joints) or Kanchanara Guggulu (thyroid).',dosage:'500mg–1g purified guggul extract twice daily with meals. Always use pharmaceutical-grade purified resin.',warn:'Avoid in pregnancy. May interact with thyroid medication and blood thinners. Do not use raw/unpurified guggul.',sci:'Guggulsterone blocks FXR (farnesoid X receptor) — exact same molecular target as modern cholesterol drugs. Multiple human RCTs confirm significant LDL reduction (15–30%). Also inhibits NF-κB and reduces platelet aggregation.',tags:['Cholesterol','Joints','Weight','Thyroid','Arthritis']},
{name:'यष्टिमधु',ro:'Yashtimadhu',en:'Licorice Root',lat:'Glycyrrhiza glabra',rasa:'Sweet',guna:'Heavy, Oily',effect:'Vata-Pitta balancing',dosha:'Reduces Vata & Pitta',when:'Sore throat, cough, acid reflux, stomach ulcers, adrenal fatigue, hyperpigmentation, hoarseness of voice.',how:'½ tsp powder in honey for throat. In milk for gastric issues. As herbal tea for respiratory. Topical licorice extract cream for skin brightening.',dosage:'1–3g root powder OR 200–600mg extract daily. Do not use continuously for more than 4–6 weeks without a 2-week break.',warn:'High doses significantly raise blood pressure — avoid entirely in hypertension. Avoid in kidney disease and during pregnancy. Do not combine with corticosteroids.',sci:'Glycyrrhizin is anti-viral against herpes simplex, hepatitis C, and SARS-CoV-1 (in vitro). Glabridin inhibits H. pylori (primary cause of stomach ulcers). Topical glabridin inhibits melanin synthesis — clinically proven skin brightener.',tags:['Throat','Acidity','Ulcer','Skin','Cough']},
{name:'गिलोय',ro:'Giloy',en:'Heart-Leaved Moonseed / Guduchi',lat:'Tinospora cordifolia',rasa:'Bitter, Astringent',guna:'Heavy, Oily',effect:'Tridoshic',dosha:'Balances all 3 doshas',when:'Fever (dengue, chikungunya, malaria), low immunity, diabetes support, liver disease, post-COVID recovery.',how:'30ml fresh Giloy stem juice daily. OR 1–2 inch fresh stem boiled in 2 cups water, reduce to 1 cup. Capsule form (500mg) twice daily.',dosage:'300–500mg extract twice daily OR 30ml fresh stem juice. For acute fever: fresh juice is most potent.',warn:'May lower blood sugar significantly — monitor if on diabetes medication. Avoid during pregnancy. Very rare: autoimmune hepatitis at high doses in susceptible individuals.',sci:'Proven immunomodulator: increases macrophage phagocytic activity by 40–60%. Berberine has proven anti-malarial activity. Used in AYUSH Ministry\\\\\'s COVID recovery protocol. 300+ peer-reviewed papers.',tags:['Fever','Immunity','Diabetes','Liver','Dengue']},
{name:'शंखपुष्पी',ro:'Shankhpushpi',en:'Bindweed / Morning Glory',lat:'Convolvulus pluricaulis',rasa:'Bitter, Astringent, Sweet',guna:'Oily, Slimy',effect:'Reduces Vata and Pitta',dosha:'Reduces Vata & Pitta',when:'Anxiety, insomnia, poor memory, mental exhaustion, stress-related headaches, children\\\\\'s learning support.',how:'Shankhpushpi syrup: 1–2 tsp twice daily. Or ½ tsp powder in warm milk at bedtime. Best taken at night for sleep and memory consolidation.',dosage:'250–500mg extract OR 1–2 tsp syrup twice daily. Children: half adult dose with milk.',warn:'Avoid with phenytoin (anti-epileptic drug) — reduces its effectiveness. May potentiate sedatives and sleep medication. Avoid while driving.',sci:'Scopoletin and convolvine modulate GABA-A receptors (same receptor as benzodiazepines) via a gentler, non-habit-forming mechanism. Scopoletin also inhibits serotonin reuptake — mild natural SSRI-like activity. Improves long-term potentiation in hippocampus in animal models.',tags:['Anxiety','Sleep','Memory','Brain','Mental Health']}];

const ARTHA=[
{num:1,sk:'विनयाधिकरण',ti:'Vinayādhikaraṇa',topic:'Training of the King',desc:'The foundation of everything. A ruler who cannot discipline himself cannot discipline a kingdom. Covers the king\\\\\'s daily routine, education from birth, control of the six senses, and the dangers of acting from desire or anger. Chanakya argues the king\\\\\'s first conquest must always be of himself.',sutra:'"In the happiness of his subjects lies the king\\\\\'s happiness; in their welfare, his welfare. He shall not consider as good only that which pleases him but treat as good also that which pleases his subjects."',mod:'Modern leadership psychology: self-regulation and emotional intelligence are the single strongest predictors of leadership effectiveness across all cultures and industries — independently confirming Chanakya\\\\\'s premise 2300 years later.'},
{num:2,sk:'अध्यक्षप्रचारणम्',ti:'Adhyaksha Pracharanam',topic:'Activities of Government Departments',desc:'A complete operating manual for a functioning state — finance ministry, treasury management, agriculture, mining, trade regulation, weights and measures, and auditing. The world\\\\\'s first civil service manual. Chanakya specifies exact record-keeping formats, inspection schedules, and anti-corruption protocols.',sutra:'"Government servants shall be paid adequately so they do not steal from the treasury. Underpaid officials are the root of all administrative corruption."',mod:'Modern public administration — particularly New Public Management reforms of the 1980s — independently arrived at the same principle: adequate compensation reduces institutional corruption far more effectively than punishment.'},
{num:3,sk:'धर्मस्थीय',ti:'Dharmasthiya',topic:'Law & Civil Courts',desc:'Civil law covering contracts, property rights, marriage, inheritance, debt, and commercial disputes. Remarkably modern: includes rules on evidence standards, burden of proof, witness examination, and explicit protections for women\\\\\'s property and inheritance rights — centuries before Roman law.',sutra:'"A contract made by fraud, coercion, or intoxication is void from the beginning. No obligation arises from an agreement extracted under duress."',mod:'This principle — vitiated consent invalidates contract — is a cornerstone of every modern legal system. The Arthashastra articulated it before any Western legal code.'},
{num:4,sk:'कण्टकशोधन',ti:'Kantaka Shodhana',topic:'Removal of Thorns (Criminal Law)',desc:'Criminal law, police operations, and intelligence methodology. Covers identification and neutralisation of criminal networks, undercover operations, entrapment law, prison administration, and investigation of financial crimes. Chanakya devotes unusual detail to fraud and embezzlement.',sutra:'"The king should identify enemies not by what they say but by what they consistently do. Speeches reveal intentions; actions reveal character."',mod:'Modern counterintelligence doctrine operates on the same principle. Behavioral analysis over verbal analysis — "actions speak louder than words" — is the foundational rule of criminal profiling.'},
{num:5,sk:'योगवृत्तम्',ti:'Yoga Vrittam',topic:'Secret & Covert Operations',desc:'The world\\\\\'s first systematic intelligence manual. Covers spy networks (four grades of agents), double agents, secret writing, coded communication, assassination, and psychological warfare. Chanakya is coldly practical: intelligence is not a luxury but the oxygen of statecraft.',sutra:'"A king\\\\\'s eye is his spy network. Without eyes, a king is blind — and a blind king is already half-defeated."',mod:'Sun Tzu covered similar ground, but the Arthashastra is more systematically organised and operationally specific. The CIA\\\\\'s intelligence community structure mirrors Chanakya\\\\\'s agent classification remarkably closely.'},
{num:6,sk:'मण्डलयोग',ti:'Mandala Yoga',topic:'Circle of States (Foreign Policy)',desc:'The "Mandala" doctrine — one of the most influential geopolitical theories ever articulated. Your immediate neighbour is your natural enemy (you compete for the same resources). Your neighbour\\\\\'s neighbour is your natural ally (you share a common enemy). This creates a circular pattern of alliances mapped with mathematical precision.',sutra:'"The enemy of my enemy is my friend. The friend of my enemy is also my enemy. These are the natural laws of statecraft, as fixed as the laws of gravity."',mod:'Balance-of-power theory in modern international relations (Morgenthau, Kissinger) is a direct re-articulation of the Mandala doctrine. NATO\\\\\'s structure and Cold War alliance systems follow Mandala logic precisely.'},
{num:7,sk:'षाड्गुण्य',ti:'Shadgunya',topic:'Six Foreign Policies',desc:'Six diplomatic instruments available to any state: Sandhi (peace treaty), Vigraha (war), Asana (neutrality), Yana (active preparation), Samshraya (seeking alliance), and Dvaidhibhava (playing two sides). A wise king uses all six — choice depends entirely on the current balance of power.',sutra:'"There is no permanent friend or permanent enemy in statecraft — only permanent interests. The wise king shifts policy as the wind shifts, always toward advantage."',mod:'Henry Kissinger\\\\\'s realpolitik doctrine is a near-word-for-word restatement of Shadgunya. Palmerston\\\\\'s famous 1848 speech ("Nations have no permanent friends, only permanent interests") mirrors Chanakya\\\\\'s sutra exactly.'},
{num:8,sk:'व्यसनाधिकरण',ti:'Vyasanādhikaraṇa',topic:'How Kings Destroy Themselves',desc:'How rulers self-destruct through seven vices: gambling, women, wine, hunting, harsh speech, excessive punishment, and wasteful spending. Most revealing is Chanakya\\\\\'s insight that a king\\\\\'s vices are not private matters — they corrupt the entire state apparatus.',sutra:'"A king who is enslaved to his own pleasures will be exploited without mercy — by his ministers, his wives, and his enemies. His weakness becomes their opportunity."',mod:'Leadership failure research: the #1 predictor of a company\\\\\'s collapse is leadership hubris combined with self-indulgence — exactly the pattern Chanakya documented. Enron, Theranos, WeWork each follow Chanakya\\\\\'s anatomy of royal self-destruction.'},
{num:9,sk:'अभियासिक',ti:'Abhiyāsika',topic:'Preparing for Invasion',desc:'Everything that happens before a single soldier crosses the border: intelligence gathering, economic strangulation, subversion of enemy alliances, recruitment of disaffected ministers, spreading disinformation, and timing invasion to coincide with internal weakness. A war won before it is fought is the only truly cheap war.',sutra:'"A war that can be won by superior diplomacy should never be won by superior arms. Arms are expensive; intelligence is cheap."',mod:'CIA Cold War doctrine of "rollback" and "containment," hybrid warfare strategy, and modern economic sanctions regimes all follow the sequential logic Chanakya documented here.'},
{num:10,sk:'युद्धविषयः',ti:'Yuddha Vishayah',topic:'Open Warfare',desc:'Conventional military doctrine — battle formations, troop compositions, terrain selection, timing of attack, coordinated use of elephants, cavalry, and infantry. Chanakya develops what is now called "combined arms doctrine" — coordinated use of different military capabilities for mutual reinforcement.',sutra:'"Fight only when the probability of victory clearly exceeds the cost of fighting. Any war where this calculation is unclear should be delayed until it tips in your favour."',mod:'Cost-benefit analysis in modern military strategy — doctrine of proportionality and decisive force theory — is the formalised version of exactly this calculation.'},
{num:11,sk:'संघवृत्तम्',ti:'Sangha Vrittam',topic:'Dealing with Republics and Oligarchies',desc:'How to interact with republics, confederacies, and guild-states — fundamentally different from dealing with monarchies. Chanakya recognises that collective decision-making entities require different strategies: divide-and-conquer, exploit internal factions, bind them with treaties serving their collective interest.',sutra:'"United, they resist everything. Divided, they can each be handled separately. The strategy against any group is always: first, find the internal crack."',mod:'Coalition management theory in international relations (managing NATO, UN coalitions, trade blocs) directly mirrors Chanakya\\\\\'s principles for dealing with confederacies.'},
{num:12,sk:'अबलविजयी',ti:'Abala Vijayi',topic:'Defeating a Stronger Enemy',desc:'The strategic doctrine for the underdog — how to defeat an enemy you cannot defeat directly. Methods: funding internal rebellions, seducing key ministers, strangling supply routes, spreading disinformation, attacking at moments of maximum internal stress.',sutra:'"Never fight a stronger enemy with equal strength. Fight them at their weakest moment, through their internal divisions, and with weapons they cannot see."',mod:'Asymmetric warfare doctrine, guerrilla strategy (Mao, Guevara, Ho Chi Minh), and modern hybrid warfare are all extensions of the principles in Book 12.'},
{num:13,sk:'दुर्गलाभोपाय',ti:'Durga Labhopaya',topic:'Capture and Building of Forts',desc:'Siege warfare and fortification doctrine. How to capture a fortified city: cut off water, subvert the garrison through bribery, create internal panic through spies, then assault at maximum weakness. Also: specifications for building an ideal capital city — sewers, 2-year granary, multiple water sources, fire prevention.',sutra:'"A fort is worthless without a garrison whose loyalty is to the king, not to their salary. A garrison that fights for money will surrender for money."',mod:'Urban warfare doctrine, siege strategy, and modern city resilience planning (critical infrastructure protection) all draw on fortification principles documented in texts like Book 13.'},
{num:14,sk:'औपनिषदिक',ti:'Aupanishadika',topic:'Psychological & Mystical Warfare',desc:'Morale operations, psychological warfare, use of religious belief and omens to shape enemy behaviour. Chanakya is coldly analytical about using superstition as a weapon — manufactured prophecies, staged miracles, rumours of divine favour to demoralise enemies before battle.',sutra:'"What cannot be achieved through force can often be achieved through the manipulation of belief. Fear of the invisible is more powerful than fear of any visible army."',mod:'Psychological Operations (PsyOps) and information warfare in modern militaries. The US MISO (Military Information Support Operations) doctrine draws directly on principles Chanakya systematised first.'},
{num:15,sk:'तन्त्रसंग्रह',ti:'Tantrasamgraha',topic:'Methodology of the Arthashastra',desc:'Chanakya\\\\\'s meta-analysis of his own work — the logic behind how he organised the Arthashastra, his sources, his approach to resolving contradictions between earlier authorities, and his classification system. A rare ancient text that is self-aware about being a synthesis of prior knowledge.',sutra:'"This science has been composed by collecting and distilling as many prior sciences on statecraft as could be found. Where they disagreed, I have chosen the most practically effective position."',mod:'Systems thinking and meta-analysis methodology: the Arthashastra is a 2300-year-old example of what we now call a "systematic review" — synthesising prior knowledge with explicit methodology.'}];

const DATASETS={gita:GITA,pancha:PANCHA,ayur:AYUR,artha:ARTHA};
window.curTopic='gita';
window.curIdx=0;
window.curData=[];

/* ── BUILD CARDS ── */
window.buildGita=function(){
  document.getElementById('gita-cards').innerHTML=GITA.map((c,i)=>\`
    <div class="learn-card" style="animation-delay:\${i*.04}s">
      <div class="c-ey">Chapter \${c.num} of 18</div>
      <div class="c-sk">\${c.sk}</div>
      <div class="c-ro">\${c.ro}</div>
      <div class="c-hr"></div>
      <div class="c-ti">\${c.en}</div>
      <div class="c-pr">\${c.preview}</div>
      <div class="c-tags">\${c.tags.map(t=>\\\`<span class="c-tag">\${t}</span>\\\`).join('')}</div>
      <button class="rm-btn" onclick="window.openDetail('gita',\${i})">Read More →</button>
    </div>\`).join('');
};
window.buildPancha=function(){
  document.getElementById('pancha-cards').innerHTML=PANCHA.map((b,i)=>\`
    <div class="learn-card" style="animation-delay:\${i*.08}s">
      <div class="c-ey">Book \${b.num} of 5</div>
      <div class="c-sk">\${b.title}</div>
      <div class="c-ro">\${b.ro}</div>
      <div class="c-hr"></div>
      <div class="c-ti">\${b.en}</div>
      <div class="c-pr">\${b.desc}</div>
      <button class="rm-btn" onclick="window.openDetail('pancha',\${i})">Read Stories →</button>
    </div>\`).join('');
};
window.buildAyur=function(){
  document.getElementById('ayur-cards').innerHTML=AYUR.map((h,i)=>\`
    <div class="learn-card gc" style="animation-delay:\${i*.04}s">
      <div class="c-ey g">\${h.lat}</div>
      <div class="c-sk">\${h.name}</div>
      <div class="c-ro">\${h.ro}</div>
      <div class="c-hr"></div>
      <div class="c-ti">\${h.en}</div>
      <div style="font-size:11px;color:var(--text-dim);margin-top:3px"><span style="color:var(--green)">Taste:</span> \${h.rasa.split(',')[0]} · <span style="color:var(--green)">Effect:</span> \${h.dosha}</div>
      <div class="c-tags">\${h.tags.slice(0,3).map(t=>\\\`<span class="c-tag g">\${t}</span>\\\`).join('')}</div>
      <button class="rm-btn g" onclick="window.openDetail('ayur',\${i})">Full Guide →</button>
    </div>\`).join('');
};
window.buildArtha=function(){
  document.getElementById('artha-cards').innerHTML=ARTHA.map((b,i)=>\`
    <div class="learn-card oc" style="animation-delay:\${i*.04}s">
      <div class="c-ey o">Book \${b.num} of 15</div>
      <div class="c-sk">\${b.sk}</div>
      <div class="c-ro">\${b.ti}</div>
      <div class="c-hr"></div>
      <div class="c-ti">\${b.topic}</div>
      <div class="c-pr">\${b.desc.substring(0,110)}…</div>
      <button class="rm-btn o" onclick="window.openDetail('artha',\${i})">Read Sutra →</button>
    </div>\`).join('');
};

/* ── DETAIL ── */
window.openDetail=function(topic,idx){
  window.curTopic=topic; window.curData=DATASETS[topic]; window.curIdx=idx;
  window.renderDetail();
  document.getElementById('cards-view').style.display='none';
  document.getElementById('detail-view').style.display='block';
  document.getElementById('screen-learn').scrollTo(0, 0);
};
window.closeDetail=function(){
  document.getElementById('detail-view').style.display='none';
  document.getElementById('cards-view').style.display='block';
  document.getElementById('screen-learn').scrollTo(0, 0);
};
window.navigate=function(d){window.curIdx+=d;window.renderDetail();document.getElementById('screen-learn').scrollTo(0,0);};

window.renderDetail=function(){
  const item=window.curData[window.curIdx], total=window.curData.length, t=window.curTopic;
  document.getElementById('dh-name').textContent=item.sk||item.name||item.title||'';
  document.getElementById('dh-sub').textContent=
    t==='gita'?\\\`Chapter \${item.num} of 18\\\`:
    t==='pancha'?\\\`Book \${item.num} of 5\\\`:
    t==='ayur'?item.lat:
    \\\`Book \${item.num} of 15\\\`;

  let h='';
  if(t==='gita'){
    h=\\\`<div style="margin-bottom:28px">
      <div class="d-eyebrow">Chapter \${item.num} of 18 · Bhagavad Gita</div>
      <div class="d-sk">\${item.sk}</div>
      <div class="d-ro">\${item.ro}</div>
      <div class="d-title">\${item.en}</div>
      <div class="d-tags">\${item.tags.map(x=>\\\`<span class="d-tag">\${x}</span>\\\`).join('')}</div>
    </div>
    <div class="gold-hr"></div>
    <div class="d-sec"><div class="d-label">Key Shloka (Sanskrit)</div>
      <div class="shloka-box"><div class="sk-text">\${item.shloka.replace(/\\n/g,'<br>')}</div><div class="sk-trans">\${item.trans}</div></div>
    </div>
    <div class="d-sec"><div class="d-label">Core Lesson</div><div class="lesson-box">\${item.lesson}</div></div>
    <div class="d-sec"><div class="d-label">Modern Connection</div><div class="d-text">\${item.modern}</div></div>\\\`;
  }
  else if(t==='pancha'){
    h=\\\`<div style="margin-bottom:28px">
      <div class="d-eyebrow">Book \${item.num} of 5 · Panchatantra</div>
      <div class="d-sk">\${item.title}</div><div class="d-ro">\${item.ro}</div>
      <div class="d-title">\${item.en}</div>
    </div>
    <div class="gold-hr"></div>
    <div class="d-sec"><div class="d-label">About This Book</div><div class="d-text">\${item.desc}</div></div>
    <div class="d-sec"><div class="d-label">Core Moral</div><div class="lesson-box">"\${item.moral}"</div></div>
    <div class="d-sec"><div class="d-label">Stories Inside This Book</div>
      \${item.stories.map(s=>\\\`<div class="story-blk"><div class="story-blk-t">📖 \${s.t}</div><div class="story-blk-s">\${s.s}</div><div class="story-blk-l">💡 Lesson: \${s.l}</div></div>\\\`).join('')}
    </div>\\\`;
  }
  else if(t==='ayur'){
    h=\\\`<div style="margin-bottom:28px">
      <div class="d-eyebrow">Ayurveda · \${item.lat}</div>
      <div class="d-sk">\${item.name}</div><div class="d-ro">\${item.ro}</div>
      <div class="d-title">\${item.en}</div>
      <div class="d-meta-row">
        <span class="d-pill g">Taste: \${item.rasa}</span>
        <span class="d-pill g">Quality: \${item.guna}</span>
        <span class="d-pill g">Dosha: \${item.dosha}</span>
      </div>
      <div class="d-tags">\${item.tags.map(x=>\\\`<span class="d-tag g">\${x}</span>\\\`).join('')}</div>
    </div>
    <div class="gold-hr"></div>
    <div class="d-sec"><div class="d-label">When to Use</div><div class="d-text">\${item.when}</div></div>
    <div class="d-sec"><div class="d-label">How to Use</div>
      <div class="shloka-box g"><div class="sk-text" style="font-family:'Lato',sans-serif;font-size:16px">\${item.how}</div></div>
    </div>
    <div class="d-sec"><div class="d-label">Dosage</div>
      <div class="ayur-row">
        <div class="ayur-blk"><div class="ayur-blk-l">Recommended dose</div><div class="ayur-blk-t">\${item.dosage}</div></div>
        <div class="ayur-blk"><div class="ayur-blk-l">Effect on doshas</div><div class="ayur-blk-t">\${item.effect}</div></div>
      </div>
    </div>
    <div class="d-sec"><div class="d-label">⚠️ Caution & Contraindications</div><div class="warn-box">\${item.warn}</div></div>
    <div class="d-sec"><div class="d-label">Modern Science</div><div class="d-text">\${item.sci}</div></div>\\\`;
  }
  else if(t==='artha'){
    h=\\\`<div style="margin-bottom:28px">
      <div class="d-eyebrow">Book \${item.num} of 15 · Arthashastra</div>
      <div class="d-sk">\${item.sk}</div><div class="d-ro">\${item.ti}</div>
      <div class="d-title">\${item.topic}</div>
    </div>
    <div class="gold-hr"></div>
    <div class="d-sec"><div class="d-label">What This Book Covers</div><div class="d-text">\${item.desc}</div></div>
    <div class="d-sec"><div class="d-label">Chanakya's Sutra</div>
      <div class="shloka-box o"><div class="sk-text" style="font-family:'Lato',sans-serif;font-size:17px">"\${item.sutra}"</div></div>
    </div>
    <div class="d-sec"><div class="d-label">Modern Parallel</div><div class="d-text">\${item.mod}</div></div>\\\`;
  }

  h+=\\\`<div class="det-nav">
    <button class="nav-btn" onclick="window.navigate(-1)" \${window.curIdx===0?'disabled':''}>← Previous</button>
    <span class="nav-ctr">\${window.curIdx+1} / \${total}</span>
    <button class="nav-btn" onclick="window.navigate(1)" \${window.curIdx===total-1?'disabled':''}>Next →</button>
  </div>\\\`;

  document.getElementById('det-body').innerHTML=h;
};

/* ── TABS ── */
window.showTopic=function(id,btn){
  document.querySelectorAll('.topic-panel').forEach(p=>p.classList.remove('active'));
  document.querySelectorAll('.tab-btn').forEach(b=>b.classList.remove('active'));
  document.getElementById('panel-'+id).classList.add('active');
  btn.classList.add('active');
  document.getElementById('screen-learn').scrollTo(0,0);
};

window.buildGita(); window.buildPancha(); window.buildAyur(); window.buildArtha();
// Back button wire-up
const btnBack = document.getElementById('learn-back-btn');
if(btnBack) {
  btnBack.addEventListener('click', () => actions.goTo('landing'));
}
\`;

let indexFile = 'index.html';
let html = fs.readFileSync(indexFile, 'utf8');

const jsStartRegex = /\\/\\/ ── Learn screen wiring ────────────────────────────────────[\\s\\S]*?(?=\\/\\/ ── Init ───────────────────────────────────────────────────)/;

html = html.replace(jsStartRegex, \`// ── Learn screen wiring ────────────────────────────────────
\${JSON_DATA}
    \`);

fs.writeFileSync(indexFile, html);
console.log('index.html updated successfully with new logic (p4)');
